### ISSUE TITLE
mouse acceleration, widgets, history, default apps, etc

### ISSUE THREAD

**Issue by Flekay** [LeDragoX/Win-Debloat-Tools#102]
### Description

Add Apps to the list Remove-BloatwareAppsList
-instagram, whatsapp, tiktok, spotify, prime video etc.

option to remove the widget menu
Get-AppxPackage *WebExperience* | Remove-AppxPackage or winget uninstall --id 9MSSGKG348SP

option to enable Run dialog history (WIN + R)

option to disable mouse acceleration

optional features to enable hyper v and sandbox

tab or option to generate a script based on your selected tweaks and software 

### Reason

N/A

### Examples

N/A

**Comment by jdggraaf** [comment]
They are not installed, just links in the start menu. They download and install if you click them.

**Comment by weirdal3333** [comment]
They are not "installed", but they are stubs that can (and should) be removed clicking on them automatically installs the full version of the app. The script removes a ton of other stubs... Maybe instead of a blacklist, it should be a whitelist? Is there any good way to detect the stubs?

**Comment by LeDragoX** [comment]
> tab or option to generate a script based on your selected tweaks and software
This part will take great time, I'll leave this to the future.
