### ISSUE TITLE
Prompting error logs when user folder name path with space

### ISSUE THREAD

**Issue by PerryCodekies** [LeDragoX/Win-Debloat-Tools#103]
### Describe the Bug

For example, if my username name is `some thing`, that is with space in between, and the user folder path becomes `C:\Users\some thing`, this cause errors. I don't have the log now as I just renamed my user folder path.

### How can this issue be reproduced?

Create a user which has space in the user name, then run the script (CLI).

### Expected behavior?

Without any error log.

### Operating System

Windows 10

### Operating System Version

22H2

**Comment by LeDragoX** [comment]
The log file should help a lot, so you need to find it manually at:
`C:\Users\your_username\AppData\Local\Temp\Win-Debloat-Tools\logs`

**Comment by LeDragoX** [comment]
This used to happen to me, lets see what happens after merging...

**Comment by LeDragoX** [comment]
# It's working!!! But with small issues...

![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/27643047/8a22bba7-e2f9-47db-849b-5e5d71e4d0c9)

The user "One Two" could run the debloater, but when downloading files the name of the user folder was recognized as "ONETWO~1".

My log files are working as well, no problems here.

Btw, tested in `WINDOWS 10 PRO 22H2` machine.
