### ISSUE TITLE
Program destroyed OS

### ISSUE THREAD

**Issue by lorenzohappy19** [LeDragoX/Win-Debloat-Tools#105]
### Describe the Bug

The whole OS was destroyed.
The Windows apps were deleted (including search and weather, which some people use)

### How can this issue be reproduced?

Just apply almost all tweaks

### Expected behavior?

To only delete unessential stuff INSTEAD OF THE WHOLE FUCKING OS

### Operating System

Windows 10

### Operating System Version

22H2

### Screenshots

N/A

### Logs

N/A

### Additional Info

# **shit program**

**Comment by vleeuwenmenno** [comment]
Inappropriate issue, there's a lot of work going into making such an app. What exactly isn't working? 

And did you maybe not read the README / DISCLAIMER? Have you tried the rollback script?

**Comment by rtgOnTop** [comment]
lmao! Destroying an OS is where you make the OS unusable not where the program deletes some programs that you dont you use 24/7 and runs in the background very stupid "bug"/comment

**Comment by LeDragoX** [comment]
This is not an issue as it's all expected from a debloater, btw, thanks to the community, seeing the reactions gave me some confidence and made me smile...
