### ISSUE TITLE
Restarts Randomly without Blue screen

### ISSUE THREAD

**Issue by smt1512** [LeDragoX/Win-Debloat-Tools#108]
### Describe the Bug

after debloating, laptop restarts randomly. No blue screen.
I have tried to replicate the issue but failed to do so.
Windows11 Home x64
Ver 10.0.22621 Build 22621

I have disabled fast boot, updated graphics driver. It's a new laptop.

### How can this issue be reproduced?

I have tried to replicate the issue but failed to do so.

### Operating System

Windows 11

### Operating System Version

10.0.22621 Build 22621

**Comment by LeDragoX** [comment]
Things like BSoD happens randomly, even I got somes, but I still don't think its 100% related to the script. All of the people I know whom tested and debloated didn't got any BSoD, so it's mostly a rare thing.
