### ISSUE TITLE
Cleanup script shouldn't download and install things.

### ISSUE THREAD

**Issue by fourofspades** [LeDragoX/Win-Debloat-Tools#110]
### Describe the Bug

This breaks the core concept of what this app claims to do.  It downloads things like Chocolatey. 

### How can this issue be reproduced?

Run app as admin.

### Expected behavior?

Not bloat system further.

### Operating System

Windows 11

### Operating System Version

22H2

**Comment by electrolyte-orb** [comment]
+1 from me too.

**Comment by weirdal3333** [comment]
If chocolatey is optional for the stuff on the main page to function, then +1 from me too. The second tab uses it, so it should be a checkbox that you have to toggle to enable apps installation.
