### ISSUE TITLE
Info for each item in GUI Menu

### ISSUE THREAD

**Issue by alexfevery** [LeDragoX/Win-Debloat-Tools#112]
### Description

There should be a mouse hover over in the GUI menu that explains more about what each thing does and what effect disabling it will have.  

### Reason

A lot of features are not obvious from the title what they actually do. For example "Enable WSearch Service".

**Comment by LeDragoX** [comment]
I linked the wrong Issue in the commit ([25a2f01](https://github.com/LeDragoX/Win-Debloat-Tools/commit/25a2f01d16b63507760307ae4da76f102b131e96)), it was supposed to be #110 and #122*.

**Comment by LeDragoX** [comment]
> There should be a mouse hover over in the GUI menu that explains more about what each thing does and what effect disabling it will have.

I remember I've done a research before on mouse hover events, and this was kinda wacky, as in WinForms its a complex implementation.

I'll isolate these tweaks to "Services" category, I should have done this beforehand, but didn't payed attention.

**Comment by LeDragoX** [comment]
Adding this will increase the code complexity a lot, not worth it.
