### ISSUE TITLE
Shortcuts do not appear after I run the script

### ISSUE THREAD

**Issue by wlcvs** [LeDragoX/Win-Debloat-Tools#113]
### Describe the Bug

After I ran the script, shortcuts on the desktop of games generated by launchers like Steam, Epic and Ubisoft Connect do not appear

### How can this issue be reproduced?

Run the script with everything at default

### Expected behavior?

N/A

### Operating System

Windows 10

### Operating System Version

22H2

### Screenshots

N/A

### Logs

N/A

### Additional Info

N/A

**Comment by weirdal3333** [comment]
Double click on one of the shortcuts with a blank paper as their icon and choose "web browser" as the default option.

If that isn't your issue, try closing the script window (the one with all the checkboxes in it) and click yes to reboot.

If that isn't your you should be able to rightclick on the desktop and show desktop icons.

If these don't work, just reinstall the apps. You could probably Google how to make a shortcut on windows as well.

**Comment by LeDragoX** [comment]
This is a problem I must found a way to self-fix, this also happens with my games installed from these shops.

Found something that might help to translate this into PowerShell:
- <https://superuser.com/questions/1399190/associate-url-shortcut-file-to-open-with-an-internet-explorer-win-10-pro>

**Comment by LeDragoX** [comment]
I noted that this won't happen in Windows 11 at all, even if I wiped everything possible within the script.
![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/27643047/5a1c1cf7-02ba-45f0-81a6-7205a3ab8738)

**Comment by LeDragoX** [comment]
Confirmed, this only happens with Windows 10!

![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/27643047/a85522c2-b8e9-4d93-be0e-2c45e0b8e110)

Now I'll be able to fix this issue.
