### ISSUE TITLE
NOT RECOMMENDED, THIS WILL BREAK MANY THINGS

### ISSUE THREAD

**Issue by neoOpus** [LeDragoX/Win-Debloat-Tools#120]
### Describe the Bug

After Installing a fresh windows and configuring it which took me several days, I tried this and now I have issue launching some installers, softwares... and I am unable to fix that as it appears that it has altered some core features. Now I have to start all over...

### How can this issue be reproduced?

just use the tweaker

### Operating System

Windows 11

### Operating System Version

23H2

**Comment by weirdal3333** [comment]
You've provided no screenshots or explanation of any specific thing that "doesn't work". This script does not have the capability to mess with your system in the way you describe. It sounds like your "multiple days of configuring" may have broken the system, instead. 

If you're setting up your system, run the debloater FIRST. It won't break anything. I just tried it in a VM.

**Comment by LeDragoX** [comment]
Thanks @weirdal3333, this is not the first time i've seen an issue like this (#105).

So @neoOpus, if you want to set up Windows your way, i'd recommend to do it after running a debloater, just like **weirdal** said.

**Comment by neoOpus** [comment]
Actually, I am highly technical and possess good expertise in Windows. I suspect that this debloater is the cause of the issue, as it is the only thing I had used before having to reinstall Windows. The previous installation had been stable for a couple of years. Despite not being certain if the debloater was the cause of the problem, I used it again after the reinstall because who wouldn't want a debloated OS?, And that caused some issues, such as being unable to install certain Adobe software. I attempted to find a solution by undoing the tweaks and trying various other methods, including reinstalling all runtimes.etc etc However, there is still an issue, and I don't see any alternative solution aside from reinstalling everything from scratch. I neglected to create a backup because I considered it unnecessary while performing multiple installations and modifications to the operating system.

**Comment by neoOpus** [comment]
My mistake I should've noticed that it only support 22H2 or older... I am using 23H2

**Comment by LeDragoX** [comment]
I imagined that you knew a lot about Windows, and the funny thing is, you tried 23H2 before launch, because of the day of this issue...
Anyway, which Adobe Software were you using @neoOpus? I wanna test on my machine.

**Comment by nopeless** [comment]
@neoOpus just backup the fresh windows partition its probably less than 100GB. I understand the frustration but you are blaming on a tool. Besides, its open source so why not just pinpoint the exact services and components that are supposed to be there but removed by the tool and make a pull request

**Comment by neoOpus** [comment]
I am mostly reporting the issue, I took the risk and I assume it! I tried to fix it, I used to have a fresh windows every month but I am not that person anymore and configuring a machine takes me days so that's part of why I wrote this "bug report", I didn't do a backup and I didn't make the required attention to the readme... this tool or any other debloater comes with a risk that something get broken but some can be easily fixed some other just require redoing all from scratch... I am still trying to find a solution and learn from it but mostly I will just reinstall all during this week, and yeah part of why I didn't backup is because my NAS is down since, my other storage full or bricked and I am too depressed (like seriously to not even be able to work or get up) to do soldering and other things other than tinkering with software in this laptop (I hope I will get better in the coming days or weeks)... so I can find a job as I need one for the moment (remote), meanwhile I am doing a lot of testing and breaking and bug fixing, reporting in GH until then.

I apologize for this frustration-induced issue report.

**Comment by LeDragoX** [comment]
I kinda know how that feels, you're not alone on that. And yeah... Windows can get janky sometimes.
I really hope you can get through this and keep persisting, just believe in yourself and think about how long you've reached, i don't know exactly what parts of the system your installed softwares needed, and i'm sorry about that.

It's fine that you let me know your frustation, this isn't perfect or a silver bullet to "fix all problems on Windows", i didn't made these tools intending to fool others, just to solve most problems i've found on Windows and reuniting a lot of tweaks altogether, so it can be better than ever (or that was what i thought).
