### ISSUE TITLE
Location services turned off ("some of these settings are managed by your organization")

### ISSUE THREAD

**Issue by corazza** [LeDragoX/Win-Debloat-Tools#133]
### Describe the Bug

It appears that this tool fiddles with the registry in some bad way, and modifying various Windows system options becomes disallowed after de-bloating. In particular, I can no longer change my location settings: instead, I see a message that "some of these settings are managed by your organization" and the settings dialogues are greyed out.

How can I fix this?

### How can this issue be reproduced?

Run de-bloat, check location settings in Windows 11

### Operating System

Windows 11

### Operating System Version

22H2

**Comment by JCenatus** [comment]
Same issue there 😢

**Comment by JCenatus** [comment]
To solve this problem, you can import an .reg file into the Windows registry:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors]
"DisableLocation"=dword:00000000
"DisableWindowsLocationProvider"=dword:00000000
"DisableLocationScripting"=dword:00000000
```

Thanks a lot @cspencer49519

**Comment by corazza** [comment]
@cspencer49519 Do you know a similar fix for automatically installing Windows Defender updates? I believe this software also messed that up. It used to be automatic, but now I get a daily notification about these small security updates, and I have to open Settings and install it manually.

**Comment by LeDragoX** [comment]
> It appears that this tool fiddles with the registry in some bad way, and modifying various Windows system options becomes disallowed after de-bloating. In particular, I can no longer change my location settings: instead, I see a message that "some of these settings are managed by your organization" and the settings dialogues are greyed out.

This was happening due to ShutUp10 configs, I'll add a proper fix to that, and another option.

> Do you know a similar fix for automatically installing Windows Defender updates? I believe this software also messed that up.

Yup, this was messed up, sorry, the default settings will wipe the previous changes on the registry, unless someone want to manually disable automatic updates.
