### ISSUE TITLE
Support Windows 11 23H2

### ISSUE THREAD

**Issue by SesioN** [LeDragoX/Win-Debloat-Tools#137]
### Description

The documentation only mentions supporting up to Windows 11 22H2.

Please support Windows 11 23H2 as the update has now officially been released.

PS:
I did not try running the script on my windows install without you saying that it's fine.

### Reason

Because all of us will be running Windows 11 23H2 sooner or later.

**Comment by Newr0n** [comment]
This is a great tool. I would love to use it under Windows 11 23H2.

**Comment by grunkl** [comment]
It works for me under 23H2
