### ISSUE TITLE
Cannot add language?

### ISSUE THREAD

**Issue by amakuramio** [LeDragoX/Win-Debloat-Tools#142]
### Describe the Bug

I want to add any other language on the keyboard. I can scroll but selecting freezes the app and typing also not working

### How can this issue be reproduced?

Go to settings, language, add language

### Operating System

Windows 11

### Operating System Version

25997

**Comment by LeDragoX** [comment]
I do not offer support for Windows Insider builds. (https://blogs.windows.com/windows-insider/2023/11/15/announcing-windows-11-insider-preview-build-25997-canary-channel/)

Current OS version (Windows 11): `22631.xxx`
Windows Insider versions tend to be unstable, which is the reason it's not worth the time.
If you want to fix that issue, then you should consider returning to [standard versions](https://www.microsoft.com/software-download/windows11) `[microsoft.com]`, have a good day!

**Comment by LeDragoX** [comment]
Other possible solution, has I tought a little more, is the `Repair Windows` button inside the script, it's located at the first page, scrolling down.

> [!NOTE]
> Outside the Insider builds, I could normally change the language

![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/27643047/3d200175-a418-4b31-aa9d-ef3482983ce9)

**Comment by amakuramio** [comment]
Thank you for your swift response, I will try to undo the tweaks, and after that find the repair button, add languages then apply the tweaks again, let's see...

**Comment by amakuramio** [comment]
Undoing the tweaks fixed it, I can add languages again
![20231125_150045](https://github.com/LeDragoX/Win-Debloat-Tools/assets/6065170/3993d6b3-8cf0-4797-8038-3b9acab75706)
