### ISSUE TITLE
The scrolling direction of my mouse wheel has inverted after running the script

### ISSUE THREAD

**Issue by sentientlantern** [LeDragoX/Win-Debloat-Tools#143]
### Describe the Bug

After running the script and restarting, my mouse wheel now scrolls in the opposite direction than it's supposed to. It now scrolls the same way it would when using a Mac.
I can't think what aspect of the script could have caused this but it happened right after I ran it. This may not even be a bug, just something I'm not aware of. I've attempted to change FlipFlopWheel in the registry but to no effect. Presumably something is overriding that.

### How can this issue be reproduced?

Scrolling the mouse wheel. This has been permanent and can be reproduced every time.

### Expected behavior?

Web pages, sliders, knobs etc should scroll in the direction that the mouse wheel is scrolled as per Windows defaults.

### Operating System

Windows 11

### Operating System Version

23H2

**Comment by LeDragoX** [comment]
I guess you've clicked on `"Enable Mouse Natural Scroll"`
![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/27643047/685f667e-e014-4e15-83ce-d255dba02c6e)

***To solve that, just click on it twice, it should disable that tweak permanently, then reboot.***

**Comment by LeDragoX** [comment]
~~At least you didn't payed an overpriced Graphics Card in pre-order, which took 2 months to tranport, then the prices got cut.~~ (me 🤡)

**Comment by MDeca001** [comment]
Hi, I tried both enabling and disabling the feature, but in every case the scrolling direction is the same (reversed), even after rebooting. What could be the issue?
