### ISSUE TITLE
Time always wrong after reboot

### ISSUE THREAD

**Issue by mmeister86** [LeDragoX/Win-Debloat-Tools#149]
### Describe the Bug

I used this Debloater several times already but this time something has gone wrong. No matter what i set in the settings, time will always be wrong (-1 hour) after rebooting. I have already reset the windows time service in the services manager but that does not seem to solve the issue.

Its a bit annoying, since every PC in my house shows the right time and even when i boot my PC into Linux the time is right. What could've gone wrong?

### How can this issue be reproduced?

1. Set time correctly
2. Reboot
3. Time is set wrong (-1h)

### Operating System

Windows 11

### Operating System Version

22H2

**Comment by weirdal3333** [comment]
Linux uses sets the RTC to UTC time, Windows sets the RTC to whatever timezone you have set. This is bad windows behavior. I agree that this needs to be fixed windows-side, but Microsoft has done such a good job forcing this to be an issue for over 20 years.

A workaround: Set clock 1 to UTC on windows, and set Clock 2 to be default AND your timezone.

**Comment by mmeister86** [comment]
It works now, either me switching the boot order in UEFI to #1 Windows and #2 Linux or latest Windows update did the trick. Thx for the help anyway!
