### ISSUE TITLE
help

### ISSUE THREAD

**Issue by YashSoPro** [LeDragoX/Win-Debloat-Tools#152]
### Describe the Bug

hey i didnt knew exactly about this it installed idk what and i wanna remove it now pls help

### How can this issue be reproduced?

idk

### Operating System

Windows 11

### Operating System Version

23H2

### Logs

[WinDebloatTools-2024-03.log](https://github.com/LeDragoX/Win-Debloat-Tools/files/14468566/WinDebloatTools-2024-03.log)

**Comment by nunessdev** [comment]
First of all, please don't run scripts/programs if you don't understand what they do to you computer! This is an important internet rule :)

If you want to revert any changes made by the script you can simply follow the steps listed in the [README](https://github.com/LeDragoX/Win-Debloat-Tools) of the main page, in the **Usage** and **Roll-Back** sections.

Alternatively, and if you really don't understand or you can't follow the steps, you can always reinstall your operating system.

**Comment by LeDragoX** [comment]
Thanks @nunessdev, for letting him know what he did wrong, and how to solve the problem in his PC.

Again @YashSoPro, please don't run if you don't want to debloat your computer, then throw a issue which has nothing to do with it's functionality. I'm trying to not be rude, but it is what it is.

It's simple the meaning of the script:
- Remove bloatware Apps 
- Disable Unused Services
- Disable Unused Scheduled Tasks
- Disable Unused Optional Features
- Disable Telemetry a LOT
- Use Adwcleaner to scan for adwares and shutup10 to do other tweaks the script won't.
- Remove old Windows Features
- Do some changes on the UI/UX
- Apply tweaks to improve performance
