### ISSUE TITLE
Sleep option is completely missing

### ISSUE THREAD

**Issue by TheCommandoChicken** [LeDragoX/Win-Debloat-Tools#158]
### Describe the Bug

The option to put my computer to sleep has completely vanished from the start menu and power settings. Not even the built in sleep button does anything. This is with "Enable Hibernate" checked.

### How can this issue be reproduced?

I applied the tweaks as default, which removed my sleep option, then attempted to re-apply them with hibernate enabled, which did not do anything.

### Expected behavior?

The option to sleep would not be removed with or without "Enable Hibernate" checked.

### Operating System

Windows 10

### Operating System Version

22H2

### Logs

[WinDebloatTools-2024-04.log](https://github.com/LeDragoX/Win-Debloat-Tools/files/15013416/WinDebloatTools-2024-04.log)

**Comment by LeDragoX** [comment]
First, if you already checked the "Enable Hibernate" option, it should bring back at least the "Hibernate" option to the start menu. As it returns the Hibernate type to full size.

Now about the Sleep button, I've found out a solution which I'll be adding Soon™ from <https://answers.microsoft.com/en-us/windows/forum/all/how-to-restore-the-sleep-option-in-the-power-menu/4477b4a5-209d-4cbb-9d26-9f92c5bd0acd>.

Open **cmd** or **powershell** as Admin just do
```cmd
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings /v ShowSleepOption /f
```

Or change the value to "1" (I'll do this one, as I want non-destructive ways to do it)
