### ISSUE TITLE
Why "Apply Tweaks" installs NET Framework 3.5 and ASP.NET 4.8 ????

### ISSUE THREAD

**Issue by barruka** [LeDragoX/Win-Debloat-Tools#180]
### Description

The user hits "Apply Tweaks" because they want to debloat Windows... and the script installs NET Framework 3.5 and ASP.NET 4.8 ????

### Reason

The user wants to debloat the OS, and the script install useless software...

**Comment by LeDragoX** [comment]
I'll remove it, this was from a time where the script hadn't many users like now, I was using these features to play a really old game 😅.
