### ISSUE TITLE
stopped halfway through and recovery isn't working

### ISSUE THREAD

**Issue by Summeryhaddock7** [LeDragoX/Win-Debloat-Tools#41]
### Describe the Bug

it began running and then about half way through it seemed to die and take down a good bit with it as suddenly now my computer is stating i no longer have an nvidia card connected to my display, i very much so do. So i went and tried to do the recovery but i am not good at it whatsoever so I ask for help in doing so given that i am not good with computers but any sort of help is appreciated =[

### How can this issue be reproduced?

run it as directed then watch it randomly die even though you specifically avoid touching keyboard

### Operating System

Windows 10 (64-bits)

### Operating System Version

21h1

### Date Executed

2022-06-02

### Additional Info

I am sorry for bad english, very worried about computer =[[[

**Comment by LeDragoX** [comment]
I didn't get it, but at least i can ask some questions to know better the behaviour.
- Did you ran the CLI or GUI (with interactive interface) script?
  - If it was the GUI version, what steps you took, just the `Apply Tweaks` button?
- Whats your NVIDIA card?

And i didn't understood, where it "died", do you remember what was being displayed on the console?

I didn't want to kill anybody's PC, and still don't have a clue how this happened, **BUT**, maybe something driver related happenned, like a driver update from your NVIDIA GPU.
If you choose to run the script, it's better to be vigilant, from start to end on what's telling on the **PowerShell** console.

The one thing you could do besides formatting is entering on **Secure Boot**, if something is at least displayed before entering Windows.

**Comment by Summeryhaddock7** [comment]
I believe CLI 
GTX 1660 TI
it was going smoothly with everything going through then halfway through it started failing to go through as they turned red and said that they were missing.

Though, question, would I be able to run either the GUI or CLI again hopefully with it succeeding this time, would I then be able to undo it?

**Comment by Summeryhaddock7** [comment]
Okay, I'm gonna try running the GUI this afternoon once I milk my goats, and I shall try and see if i can then undo the issue, much thanks for understanding =]

**Comment by Summeryhaddock7** [comment]
SUCCESS, I had GUI in wrong place initially but very much success! Side note: nice ui design, very clear communication =]]]

**Comment by LeDragoX** [comment]
> I believe CLI GTX 1660 TI it was going smoothly with everything going through then halfway through it started failing to go through as they turned red and said that they were missing.
> 
> Though, question, would I be able to run either the GUI or CLI again hopefully with it succeeding this time, would I then be able to undo it?

You can't undo every tweak, but i made most tweaks "undoable", you just need to open the GUI, then click on Undo Tweaks, btw, nice GPU.

> SUCCESS, I had GUI in wrong place initially but very much success! Side note: nice ui design, very clear communication =]]]

Congrats and thanks, i tried my best when making the design, because `Win Forms` looks so sluggish and old ;)
