### ISSUE TITLE
Dont include Onedrive and encrpyted DNS by default

### ISSUE THREAD

**Issue by starraiderx** [LeDragoX/Win-Debloat-Tools#45]
### Description

Both encrypted DNS and Onedrive shouldn't be enabled/deleted by default since it is not necessarily an improvement for the user, depending on the configuration. Instead, there should be a checkbox for both of them to have them enabled or not when running the script.

### Reason

For example, someone could use a pi-hole as their DNS server or some Adult filtering DNS server, so changing the DNS records is not an "improvement" for them.

The same goes for OneDrive; many people rely on it as their cloud storage, so it should only be deleted when the user has been asked before.

**Comment by LeDragoX** [comment]
I agree that using other DNS may not improve anything and vary depending on where u are, it feels more like an placebo effect as it a specific tweak i did to test. It puts the DNS from **Google** and **Cloudflare**. I did this tweak a while ago, before Win 11, as MS was releasing the **DNS over HTTPS** feature, and i was curious about it. I still don't know if it really enables that or not, as it should be more safe than not using on Win 10 Insider / Win 11.

As for OneDrive, it happened that some of my local testers used OneDrive, but it comes with Windows, running on the background, leaving has an option may be better for all scenarios.

**Comment by LeDragoX** [comment]
### Ready to push

![image](https://user-images.githubusercontent.com/27643047/178065234-382646d3-9832-4880-9441-e2743cc549f5.png)

**Comment by starraiderx** [comment]
I agree with you on one drive. I suggest adding a similar button to the encrypted DNS one: "Don't uninstall Onedrive."
Maybe you could even make a whole section of apps not to uninstall, with checkboxes and such.

**Comment by LeDragoX** [comment]
These apps aren't auto-generated yet, but can be found on the [src/scripts/remove-bloatware-apps.ps1](https://github.com/LeDragoX/Win-Debloat-Tools/blob/main/src/scripts/remove-bloatware-apps.ps1). But can be manually commented on your script run, to avoid uninstalling (if this is what you meant).
