### ISSUE TITLE
`Manually` select tweaks and Add `Windows Media Player` (new) tweak

### ISSUE THREAD

**Issue by Nirgranth** [LeDragoX/Win-Debloat-Tools#48]
### Description

Add a list of settings where you can choose the tweaks you want to perform

### Reason

Windows media player and other important features removed

**Comment by Nirgranth** [comment]
new one because i used the hover feature 
![image](https://user-images.githubusercontent.com/48947296/178577539-319ee67b-fb04-4bf6-9e94-aabf604eda12.png)

**Comment by LeDragoX** [comment]
I went sick right after the moment i've answered u, sorry for the delay. I've updated another essential stuff on the project first, to help get this done quickly.

**Comment by LeDragoX** [comment]
> Freatures that i want that are removed- ZuneMusic (MSstoreapp) Xbox Paint3D Paint Sound Recorder DolbyAudio Game Bar & Game DVR Widgets (Taskbar) Search for App in Store for Unknown Extensions Printing-PrintToPDFServices-Features Printing-XPSServices-Features
> 
> Thats why a wanted a way to manually select
I'll continue on the other day.
But i got one question after your comment, did it removed the Win 11 UWP paint?

> Game Bar & Game DVR
- Xbox Game Bar wasn't removed, only if you executed "Remove Xbox"

> Search for App in Store for Unknown Extensions
- I'll research this tomorrow

> Widgets (Taskbar)
- Already got it on the Readme as "⚡ Troubleshooting Known Issues" [link](https://github.com/LeDragoX/Win-Debloat-Tools#-troubleshooting-known-issues)
  - but will add this to the script GUI later.

> DolbyAudio
- is this the APP you're searching? <https://www.microsoft.com/store/productId/9NJZD5S7QN99>

The rest i didn't talked i know a way to bring back safely, so stay calm till tomorrow, thanks for the suggestions.

**Comment by Nirgranth** [comment]
> * Xbox Game Bar wasn't removed, only if you executed "Remove Xbox" 
Remove by cli

> The rest i didn't talked i know a way to bring back safely, so stay calm till tomorrow, thanks for the suggestions.
No worries i can just fresh install anyways

**Comment by LeDragoX** [comment]
_Sent the update to the `main` branch now! You can see and close the issue if it's solved._

**Comment by Nirgranth** [comment]
> new one because i used the hover feature ![image](https://user-images.githubusercontent.com/48947296/178577539-319ee67b-fb04-4bf6-9e94-aabf604eda12.png)

although the ,edia player is back this issue remains

> Xbox and Dolby Audio
![image](https://user-images.githubusercontent.com/48947296/180092837-680f6d63-190b-42a3-be08-62a99db3c6c9.png)


> Printing-PrintToPDFServices-Features 
> Printing-XPSServices-Features
> Search for App in Store for Unknown Extensions
Missing

**Comment by LeDragoX** [comment]
> although the media player is back this issue remains

Maybe needs the older WMP, i'll let users install that again.

**Comment by LeDragoX** [comment]
About the Xbox apps, it's a big trouble, if you choose to `Remove Xbox`, getting it back does not guarantee anything.
Dolby Audio will only install on "Licensed Devices" whatever that means.
These 3 last features you mentioned are ON the GUI, don't say it's missing cause it **isn't**

**Comment by LeDragoX** [comment]
Please check `Develop` download, and use the GUI, cause the modifications happens over there.

**Comment by Nirgranth** [comment]
> These 3 last features you mentioned are ON the GUI, don't say it's missing cause it **isn't**

My bad dint see

> Please check `Develop` download, and use the GUI, cause the modifications happens over there.

Thanks
