### ISSUE TITLE
Window `size` of GUI

### ISSUE THREAD

**Issue by xargon666** [LeDragoX/Win-Debloat-Tools#51]
### Describe the Bug

When I launched the GUI it seems to have a fixed window width of several thousand pixels, possibly because I am running three monitors? The window size appears to be unchangable.

### How can this issue be reproduced?

run the gui from powershell as instructed, fresh win10 install.

### Operating System

Windows 10

### Operating System Version

10.0.19044

### Date Executed

25-JULY-2022

**Comment by LeDragoX** [comment]
I've tried a fix, this is not the first time someone talked about this issue, maybe this time it's partially solved.
Just download from the `develop` branch and see if it's better @xargon666

**Comment by LeDragoX** [comment]
I need you here @MattRay0295 , if you want to help, there's a new opportunity, this guy whom created the issue doesn't seem to respond, but you helped a lot on thinking about scaling.

The only thing you gotta do is try to open the `develop` version to see if it's scaling properly.

You're not obligated to do if you don't want. But by doing this I'll merge the update to the main branch if everything is correct.
