### ISSUE TITLE
Script to remove new weather app in task bar

### ISSUE THREAD

**Issue by nekopep** [LeDragoX/Win-Debloat-Tools#56]
### Description

New windows 10 version add a weather app in bottom right of the task bar.
After applying your script in CLI mode I saw this weather app was not removed.
Please find below a powershell I used to remove it (after reboot)

### Reason

Just remove uneeded noise of weather :)

### Examples

$registryPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds"
$Name = "EnableFeeds"
$value = "0"
if (!(Test-Path $registryPath)) {
        New-Item -Path $registryPath -Force | Out-Null
        New-ItemProperty -Path $registryPath -Name $name -Value $value -PropertyType DWORD -Force | Out-Null
}
else {
        New-ItemProperty -Path $registryPath -Name $name -Value $value -PropertyType DWORD -Force | Out-Null
}

**Comment by LeDragoX** [comment]
This tweak you said is already on the script, BUT, only on the current user, i'll modify to that, as it changes on all users (local machine)
_After that all users will hide News and Interest_

Old key: 
```ps1
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds" -Name "ShellFeedsTaskbarViewMode" -Type DWord -Value 2
```

New key:
```ps1
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds" -Name "EnableFeeds" -Type DWord -Value 0
```

Thanks!

**Comment by LeDragoX** [comment]
This part should be explained too, after doing this tweak, restarting `explorer.exe`, the user cannot bring back by just right-clicking the taskbar as it hides the option to _News And Interest_.

But it can be undone by using the "**Undo Tweaks**" option through GUI
