### ISSUE TITLE
Script to remove Windows 10 April 2022 search Highlights

### ISSUE THREAD

**Issue by nekopep** [LeDragoX/Win-Debloat-Tools#57]
### Description

Windows 10 April 2022 update added a new search highlights
The script below remove they search highlight. (need  logout/login)
see https://4sysops.com/archives/turn-off-windows-search-enhancements/ for example.

### Reason

No more distraction!

### Examples

New-Item "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Force
New-ItemProperty "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "EnableDynamicContentInWSB" -PropertyType DWORD -Value 0

**Comment by LeDragoX** [comment]
This feature was already missing for me because my search box is always hidden 😅.
Thanks for this tweak too!
