### ISSUE TITLE
Readme still says 21H2, is this still a thing?

### ISSUE THREAD

**Issue by weirdal3333** [LeDragoX/Win-Debloat-Tools#59]
### Describe the Bug

Readme says 21h2

### How can this issue be reproduced?

Look at readme

### Expected behavior?

Pretty sure the script works on 22h2

### Operating System

Windows 11

### Operating System Version

22h2

### Additional Info

I've had friends use your script on windows 11 22h2 and it works. Is the readme out-of-date?

**Comment by LeDragoX** [comment]
I'll wait til' 22H2 is officially released, but yeah, i've tested it without any problems, it just sucks to have unsuported hardware (Ryzen 1000 series) :/

**Comment by jdggraaf** [comment]
Why would Ryzen G1 be a problem? There are a lot of workarounds here on GitHub. Personally I used Aveyo's script. Highly recommend it.

**Comment by LeDragoX** [comment]
> Why would Ryzen G1 be a problem?

In my case i got some hardware problems that trigger BSoD easily in Win 11, so i'll keep on 10 until it reaches 2 years after launch...

I used W11 at launch, maybe it's a small trauma i got over there. I know either other workarounds to get it working, i'm just waiting for more stability.

**Comment by LeDragoX** [comment]
Today is the **day**, got Win 11 22H2 ISO to test.

**Comment by LeDragoX** [comment]
Used on this version with all updates installed, working fine.

![Win11Ver](https://user-images.githubusercontent.com/27643047/191615249-af07689c-736f-4748-989e-b76bde9c70f7.png)
