### ISSUE TITLE
Add `Natural Scroll` option

### ISSUE THREAD

**Issue by vbalien** [LeDragoX/Win-Debloat-Tools#63]
### Description

Option to change scroll direction. Sorry if it already exists.

### Reason

I want to use the same scrolling direction for both Mac, Linux and Windows.

### Examples

https://answers.microsoft.com/en-us/windows/forum/all/set-the-mouse-scroll-direction-to-reverse-natural/ede4ccc4-3846-4184-a86d-a028515040c0

**Comment by LeDragoX** [comment]
Added this option to the `develop` branch. Just download to test it, you shall restart your PC after applying and get the same mouse scrolling as mac.

![image](https://user-images.githubusercontent.com/27643047/191283028-e5f5d73f-a09f-4d2a-9595-4abca29a9fac.png)

If this is working as you expected i'll merge to the `main` branch

**Comment by vbalien** [comment]
Yes, this works as I expected. Thank you.
