### ISSUE TITLE
Windows stopped `sharing clipboard history` across devices

### ISSUE THREAD

**Issue by mintgh** [LeDragoX/Win-Debloat-Tools#67]
### Describe the Bug

After running the debloat script, I can no longer share the clipboard history between 2 Windows computer logged in the same Microsoft account.

### How can this issue be reproduced?

1. Run debloat script.
2. Copy from machine 1
3. Paste in machine 2
4. Unable to paste

### Expected behavior?

Machine 2 should be able to get a copy of the machine 1 clipboard and paste it on machine 2.

### Operating System

Windows 11

### Operating System Version

21H1

**Comment by MadhiasM** [comment]
Did you try enabling it with regedit?
https://www.tenforums.com/tutorials/109803-turn-off-clipboard-sync-across-devices-windows-10-a.html
https://www.elevenforum.com/t/enable-or-disable-clipboard-sync-across-devices-in-windows-11.976/

**Comment by LeDragoX** [comment]
@mintgh please re-download from `develop` branch, it contains the additions required.
![image](https://user-images.githubusercontent.com/27643047/196778901-147811b4-ab5b-45c4-9c9d-cc07bfa70222.png)

**If this doesn't work, you should change from gpedit.msc from [here](https://www.elevenforum.com/t/enable-or-disable-clipboard-sync-across-devices-in-windows-11.976/#Three) as cited from Madhias**
