### ISSUE TITLE
Clipboard history cannot be enabled even when enabling it in GUI

### ISSUE THREAD

**Issue by MadhiasM** [LeDragoX/Win-Debloat-Tools#69]
### Describe the Bug

Clipboard history is greyed out ("manage by my organization") eventhough I enabled it in the GUI before applying tweaks

### How can this issue be reproduced?

1. Run GUI
2. Click "✅ Enable Clipboard History"
3. Click "✔️ Apply Tweaks"
4. Wait for script to finish
5. (Optional) Restart system
6. Try to use Cliboard with "Ctrl" + "V"
7. Open clipboard settings

### Expected behavior?

Expected behaviour
1. Clipboard history opening with "Ctrl" + "V"
2. Clipboard settings being accessible and changeable or at least clipboard history being enabled

Observed behaviour
1. Emoji Selector will open (Usually is "Ctrl" + ".")
3. Settings are greyed out, disabled and "managed by my organization"

### Operating System

Windows 11

### Operating System Version

21H2

### Screenshots

What opens instead on "Ctrl" + "V":
![image](https://user-images.githubusercontent.com/47840254/196031816-12c168a1-ab1a-41b9-8b34-c243f2f8624a.png)

Greyed out clipboard settings
![image](https://user-images.githubusercontent.com/47840254/196031485-29c2733d-b92e-4d12-a5d7-90211a0ab271.png)

**Comment by MadhiasM** [comment]
Solver by manually running the Enable-ClipboardHistory commands in PowerShell:

Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "AllowClipboardHistory" -Type DWord -Value 1
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Clipboard" -Name "EnableClipboardHistory" -Type DWord -Value 1

, checking the values of that path in regedit and restarting the system

**Comment by LeDragoX** [comment]
So, i got this misunderstood. 
- You need to **apply the tweaks first**,
- then **customize what you need**,
(which, in this case enabling _Clipboard history_)

![image](https://user-images.githubusercontent.com/27643047/196038354-8920021a-33d1-44dc-95f3-5646308e4140.png)

Doing it in this order will avoid any doubts.

By the way, the restart is **needed** to this to work.

**Comment by MadhiasM** [comment]
Good to know, I did it the other way around, thanks for the info
