### ISSUE TITLE
Disable Bing Search in Start Menu

### ISSUE THREAD

**Issue by MadhiasM** [LeDragoX/Win-Debloat-Tools#70]
### Description

To disable Bing search in the start menu in Windows 10 version 2004 or later, the following steps need to be done:

For Windows 10 version 2004 or later:
1. Navigate to "HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows" on the left side of the Registry Editor window.
2. If the key "Explorer" already exists below the key "Windows", click on it. Otherwise, create this key by right-clicking on "Windows" and clicking on "New" -> "Key". After you've entered the name "Explorer", confirm it by pressing Enter.
3. Then right-click in the free area on the right and create another DWORD value by clicking on "New" -> "DWORD (32-bit) Value". Type "DisableSearchBoxSuggestions" for the name and press Enter.
4. Double click on this new entry and set the value to 1. Confirm the change by pressing Enter.
5. Reboot

Source:
[](https://www.bennetrichter.de/en/tutorials/windows-10-disable-web-search/)

This could be done analogously in PowerShell:

```
function Disable-BingSearch() {
    Write-Status -Types "-", "Misc" -Status "Disabling Bing Search in Start Menu..."
    If (!(Test-Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\Explorer")) {
        New-Item -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\Explorer" -Force | Out-Null
    }
    Set-ItemProperty -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\Explorer" -Name "DisableSearchBoxSuggestions" -Type DWord -Value 1
}

```

### Reason

Current implementation only sets "CortanaConsent" and "BingSearchEnabled" in "KEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" to 0. This is not sufficient for newer Windows versions.

**Comment by LeDragoX** [comment]
@MadhiasM I've inserted this suggestion into the code, just re-download from the `develop` branch, its inside **apply tweaks** or **personal-tweaks.ps1** file if your want a quick test.
```ps1
.\src\scripts\personal-tweaks.ps1 # to run
```

**Comment by MadhiasM** [comment]
Worked great when running personal-tweaks.ps1. Is there any way to enable the tweak in the GUI version?

**Comment by LeDragoX** [comment]
> Is there any way to enable the tweak in the GUI version?

I'm not planning to do that...sorry
