### ISSUE TITLE
Can connect to wifi but cannot use internet everything is TIMED OUT

### ISSUE THREAD

**Issue by justinr1234** [LeDragoX/Win-Debloat-Tools#72]
### Describe the Bug

After running these tools, I can no longer connect to the internet.

Razer laptop with Windows 11.

### How can this issue be reproduced?

Run the scripts.

### Operating System

Windows 11

### Operating System Version

22H2

**Comment by LeDragoX** [comment]
You've used the `main` version, right? The only tweak that adjusted that in the main branch was the network throttling.
And maybe again the driver related behavior.

A small troubleshooting i've done to help all kinds of situations is the "Repair Windows" function i created over the GUI.
Just scroll down a little and you should find it by the left.

Sorry for the inconvenience

**Comment by LeDragoX** [comment]
If the wi-fi driver was updated you can rollback it by opening the **Device Manager**, then **Network adapters** (in which you should look to your wifi driver).
Then finally go to the Rollback driver (if it was updated)

![](https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2022/03/view-wireless-driver-info.jpg?q=50&fit=crop&w=1500&dpr=1.5)

**Comment by LeDragoX** [comment]
My final suggestion is to re-run the script, but from the `develop` branch, just below the Main, on the README file.

**Comment by justinr1234** [comment]
I had to disable the manual proxy configured. Not even sure how that happened but it was set to 190.6.74.250 port 3128

**Comment by LeDragoX** [comment]
Neither i understand why that happened, but anyway, to make things clear, the only part which would configure network is DNS.

Exactly in this part, but it does not run anymore within **Apply Tweaks** for some reasons from #45
![image](https://user-images.githubusercontent.com/27643047/203663146-d462bd36-27df-41ed-9a58-30eb1c5cd0cc.png)

But one thing which may had configured that is not detecting proxy automatically:
<https://github.com/LeDragoX/Win-Debloat-Tools/blob/main/src/scripts/optimize-performance.ps1#L97>

And this is the first time that something behaved wrong...weird

**Comment by justinr1234** [comment]
I think what happened is i had a proxy enabled previously and something in the scripts triggered it to be re-enabled somehow
