### ISSUE TITLE
`Cannot` connect to the internet 

### ISSUE THREAD

**Issue by zeroCass** [LeDragoX/Win-Debloat-Tools#74]
### Describe the Bug

The internet is available, but the connection time out on every request. Cannot use browser or everything that needs access with the internet 

### How can this issue be reproduced?

Run the script

### Operating System

Windows 10

### Operating System Version

22H2

**Comment by LeDragoX** [comment]
I think you're having the same trouble as this https://github.com/LeDragoX/Win-Debloat-Tools/issues/72#issuecomment-1325754534

And the solution "may" be turning on that option, to **automatically detect the proxy**.
