### ISSUE TITLE
Remove "Feedback Hub" bloat app

### ISSUE THREAD

**Issue by weirdal3333** [LeDragoX/Win-Debloat-Tools#75]
### Description

An app that this script misses is the windows "Feedback Hub"

### Reason

The feedback hub is a bloat app

**Comment by LeDragoX** [comment]
I was in doubt if this app would be "useful" or not. I was expecting an answer like this, so this confirms if somebody really reports something to MS.

Thanks! I'll be removing again, starting on `develop` branch.

**Comment by weirdal3333** [comment]
Nice! The feedback hub is more of a webapp that connects to one of microsoft's support forums. It has a few features in it that could allow someone to remotely gain access to a computer, as well as being something that sends data back to Microsoft periodically after you open it once.
