### ISSUE TITLE
Question: Windows update disabled?

### ISSUE THREAD

**Issue by AstragoDE** [LeDragoX/Win-Debloat-Tools#76]
### Description

In [one of the videos ](https://youtu.be/hQSkPmZRCjc) in the "[Used code references](https://github.com/LeDragoX/Win-Debloat-Tools#-used-code-references)" section, it was mentioned, that Windows updates are being disabled. Is this also the case in the "Win Debloat Tools" version that is distributed using this repository? If so, is it still possible to update Windows using the "Windows Update" Tab in the settings?

I used the Apply Tweaks Button.
I am using Windows 11 Pro. 

Thanks for the reply in advance. 

### Reason

N/A

### Examples

N/A

**Comment by LeDragoX** [comment]
Hello @AstragoDE and responding to your question: **No**, Windows Update isn't disabled, it would be problematic to do such a thing, the tweaks i did are to change driver behavior on Windows Update and let the user choose when to download and install the updates.

 _Windows Update will keep enabled as default, as it bring "security" and "resources" to Windows._

I am careful when taking Registry tweaks from YT videos, not every tweak can be trusted, as it can damage or reduce stability from the system.

**Comment by AstragoDE** [comment]
Thank you very much for the clarification. 
I will now close the issue since I see it as resolved.
