### ISSUE TITLE
opt-out toggle for automatic updates

### ISSUE THREAD

**Issue by weirdal3333** [LeDragoX/Win-Debloat-Tools#78]
### Description

A toggle or checkbox that is enabled by default for the automatic updates registry tweak.

### Reason

I personally have automatic updates on, but I have to go into the registry manually to remove the changes every time I run this script on a PC I am setting up.

Making the tweak enabled by default and having an option to disable it seems like a good idea to me.

**Comment by LeDragoX** [comment]
There's 2 things i found on Registry.
- You can select how Windows Update acts, like selecting if Windows downloads and installs an update after a CHECK manually or automatically.
- Or Enable or Disable Automatic Updates, disabling update scheduled checks and notifications (this way Windows doesn't even check if theres an available update)

The way the script is now, it just choose to download and install updates manually, but keep on automatic updates.
I'm not a huge fan of disabling totally WU automatic updates, so i'll keep it on, and reapply the default settings and keep chooseable the update method.

**Comment by weirdal3333** [comment]
I think that keeping automatic updates is a good idea for most users, but that the option for disabling them the way you have it is still an extremely good option. I was just thinking that instead of making it automatically run with all the other tweaks, you could put it in that wall of checkboxes.
