### ISSUE TITLE
Remove carbon aware crap

### ISSUE THREAD

**Issue by H3rmit** [LeDragoX/Win-Debloat-Tools#80]
### Description

Please find a way to remove the "carbon aware" crap. I'm sick of looking at it.

### Reason

It's annoying

**Comment by weirdal3333** [comment]
Context for what he's referencing: https://support.microsoft.com/en-us/windows/windows-update-is-now-carbon-aware-a53f39bc-5531-4bb1-9e78-db38d7a6df20

**Comment by LeDragoX** [comment]
I couldn't find a way to remove this.
