### ISSUE TITLE
`MouseHoverTime` registry entry gets `incorrectly` converted to DWORD.

### ISSUE THREAD

**Issue by RaulGonzalezPortillo** [LeDragoX/Win-Debloat-Tools#83]
### Describe the Bug

In line 109 from optimize-performance, the script changes the DWord entry "MouseHoverTime" to 10, from 400.

```
Write-Status -Types "+", $TweakType -Status "Reducing mouse hover time events to 10ms..."
Set-ItemProperty -Path "HKCU:\Control Panel\Mouse" -Name "MouseHoverTime" -Type DWord -Value 10 # Default: 400
```

But MouseHoverTime is originally a String Value. By changing it's type, Windows ignores this value and defaults to 0, which, for example, causes the Widgets and Task View hover events to trigger instantly if you happen to go over them while trying to reach the start button with your mouse.

### How can this issue be reproduced?

Execute the optimize-performance script.

### Operating System

Windows 11

### Operating System Version

22H2 (Build 22621.1194)

**Comment by LeDragoX** [comment]
Thanks, i didn't realized the reason which this tweak wasn't working properly, i'll test and change the type from Dword to String 😉

**Comment by KevinJamesSmirking** [comment]
Dude I think you kinda fucked up, the MouseHoverTime is set to a 1000.
Or are you doing some voodoo shit with the String?

**Comment by cakiya** [comment]
> Dude I think you kinda fucked up, the MouseHoverTime is set to "1000". Or are you doing some voodoo shit with the String?
> 
> edit: might be my sleepy ass tho so no worries

no you are right; after running script i tried to hover over some taskbar icons and it took longer than usual to appear (i use ghelper). this can be fixed by changing it to default value of 400, not 1000.
