### ISSUE TITLE
`Hibernation option` gone

### ISSUE THREAD

**Issue by bregon** [LeDragoX/Win-Debloat-Tools#85]
### Describe the Bug

Hi, after applying the tweaks the hibernation option disappears. How do I re-enable it ?

### How can this issue be reproduced?

apply tweaks

### Operating System

Windows 11

### Operating System Version

22H2

**Comment by LeDragoX** [comment]
A friend of mine had the same problem before, here's the solution:

- Open cmd or powershell as administrator and type (hit `ENTER` to apply)

```ps
powercfg /hibernate on
powercfg /h /type full
```

**Then the option should re-appear on power plans from CONTROL PANEL first, so you can manage the power buttons**
![](https://www.tenforums.com/attachments/tutorials/109997d1479068791-change-default-action-power-button-windows-10-a-change_power_button_action-1.png)

**Comment by LeDragoX** [comment]
I'll add a separate function to enable or disable hibernate properly (it's currently a mess)
But only after i got some time.
