### ISSUE TITLE
Just doesn't work, stops when gets to uninstalling "YourPhone", doesn't continue, no error messages.

### ISSUE THREAD

**Issue by Istoleyourface** [LeDragoX/Win-Debloat-Tools#86]
### Describe the Bug

When running the debloater, when it uninstalls the default windows apps, when it gets to the YourPhone app, it doesnt continue. It doesnt display an error message, it just pauses.

### How can this issue be reproduced?

1. run debloater

### Expected behavior?

this debloater should actually work

### Operating System

Windows 11

### Operating System Version

22H2

**Comment by weirdal3333** [comment]
Sounds like you clicked in the powershell window. Clicking in the window pauses any script. Pressing any key on your keyboard will unpause it.

**Comment by LeDragoX** [comment]
This could happen while removing this app, I had the same trouble before, but it was before Windows 11.
I ran this script on Windows 10 22H2 and Windows 11 22H2, and can assure you this won't happen anymore.
