### ISSUE TITLE
Onedrive uninstall but still have folder inside user

### ISSUE THREAD

**Issue by MAULIK882** [LeDragoX/Win-Debloat-Tools#87]
### Describe the Bug

When we uninstall onedrive with script or manually this will remove onedrive from everywhere expect from user profile. 

problme is desktop files save at loction /username/onedrive/desktop
and same for documents 

### How can this issue be reproduced?

go to
C:\Users\username
select Onedrive from list
Delete it  with all permission
after that when restart computer it will regenerate onedrive folder

### Operating System

Windows 11

### Operating System Version

22H2

**Comment by MAULIK882** [comment]
Solution is 
Go to
User\username\onedrive\
Right Click on **Desktop**
Go to **Properties** 
Click on **Location**
Click on **Restore to Default**

**Comment by LeDragoX** [comment]
Are you logged out from your MS account? Because it'll sync all settings while connected.

**Comment by MAULIK882** [comment]
Sorry for late reply.  I already  logout from MS account. i have checked with login id too but same result but after that i have restore location path and works fine now
