### ISSUE TITLE
HOW REMOVE Natural Scroll option ?

### ISSUE THREAD

**Issue by LeoGraciano** [LeDragoX/Win-Debloat-Tools#88]
### Description

How to remove the natural scroll option, I used the default way so much that this way is very uncomfortable for me...

I've tried several tutorials and I can't revert this option, I've tried adding again and it doesn't work.

### Reason

How to remove the natural scroll option?

**Comment by LeDragoX** [comment]
@LeoGraciano Do this, then restart your computer.

![powershell_qTZuZNjxu3](https://user-images.githubusercontent.com/27643047/221374048-c831a0a0-e3a4-434c-88e4-f25e06284d94.gif)
