### ISSUE TITLE
The GUI doesn't open

### ISSUE THREAD

**Issue by SteveeWasTaken** [LeDragoX/Win-Debloat-Tools#89]
### Describe the Bug

Whenever I try to open the GUI script just like it says on the wiki, it starts to output lots of error messages, and then it closes

### How can this issue be reproduced?

1. Run the GUI like its specified on the README
2. See the error

### Expected behavior?

The GUI should appear.

### Operating System

Windows 10

### Operating System Version

22H2

### Screenshots

![image](https://user-images.githubusercontent.com/77215030/221424705-a50f2785-2124-4d13-a8d2-91f7e5b5e765.png)

**Comment by LeDragoX** [comment]
You're in the wrong location `C:\Windows\System32\`
It should be on the same folder as the script...
...or something is really wrong, before you hit enter, what was the directory you were?

**Comment by SteveeWasTaken** [comment]
Am I supposed to be in C:\Windows\System32? Because I was on a folder I had just created with all the files in it

**Comment by LeDragoX** [comment]
The error may be related to permissions, because on this command:
```ps1
Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force; ls -Recurse *.ps*1 | Unblock-File; .\"Win10ScriptGUI.ps1"
```

The `Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force;` Allow your user to run Powershell scripts
And `ls -Recurse *.ps*1 | Unblock-File;` will make each child file with ".ps1,psm1" as extension to be able to execute without the need to **press R and ENTER** to import modules and run the needed functions.

The last one `.\"Win10ScriptGUI.ps1"` on the `main` branch is just to run the script which generates the GUI and allows mouse interactivity.

Can you send a log within the folder `%temp%\Win-DT-Logs`?

**Comment by SteveeWasTaken** [comment]
It didn't output any logs at all, that's not normal, is it?

**Comment by LeDragoX** [comment]
> It didn't output any logs at all, that's not normal, is it?

Ok, then it didn't even started properly. I don't know.

**Have you really done each step from README?**
1. Download a version
2. Extract the .zip folder somewhere
3. Run `OpenTerminalHere.cmd` which opens a new powershell window in your case, but already on the correct directory.
4. Run the command to use GUI or CLI (the entire line).

If this isn't the case, i recommend trying something different, like trying to unlock powershell to Local Machine
```ps1
Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force; ls -Recurse *.ps*1 | Unblock-File; .\"Win10ScriptGUI.ps1"
```

If something is wrong in the step 3, you can force `OpenTerminalHere.cmd` to run as admin, then it will work normally.

And if even that doesn't work, you can download the `Develop` version, which was really improved recently...but that is your last resort.

**Comment by SteveeWasTaken** [comment]
You have to extract the entire zip? That's probably why it didn't work. I only extracted the .cmd and the .ps1 files.

**Comment by LeDragoX** [comment]
> You have to extract the entire zip? That's probably why it didn't work. I only extracted the .cmd and the .ps1 files.

Yes!!! 🤣🤣🤣 **You should extract the entire zip to the script work**, it's not a standalone file like other scripts from the community.
